### ISSUE TITLE
Implement a faster APRS beacon

### ISSUE THREAD

**Issue by abagali1** [TJREVERB/pfs#75]
# Description
To ensure that we can efficiently find our satellite, implement a _fast_ APRS beacon.
 THis is similar to Iridium heartbeat but faster

**Comment by abagali1** [comment]
Related Issues: #78  #77 #76 #74

**Comment by sparthaje** [comment]
I implemented this in `start_beacon` in telemetry, let me know if its ok. @abagali1

**Comment by abagali1** [comment]
Ideally this would be a core process so that errors are propagated upwards. Use the Timer class in core like the current telemetry dump process

**Comment by sparthaje** [comment]
@abagali1 I added those changes
